services:
  builder:
    image: $registry/$tenant_name/sd-serverless:builder
    build:
      context: .
      target: builder
      args:
      - BASE_URL=$registry
  sd-serverless:
    image: $registry/$tenant_name/sd-serverless:v1
    build:
      context: .
      target: v1
      args:
      - BASE_URL=$registry

